### ISSUE TITLE
cssdoc.net transfer

### ISSUE THREAD

**Issue by josephfusco** [cssdoc/cssdoc#4]
You are probably familiar with what used to be http://cssdoc.net. The site was around since 2007 but is now abandoned and only accessible through archive.org.

See: http://web.archive.org/web/20070601200419/http://cssdoc.net/

I am working on transferring over a copy of the cssdoc.net info to GitHub and was wondering if this organization could be used for it since it holds the name "CSSDOC". It seems like this is more of a abandoned form of sass documentation as well, which is being actively developed on http://sassdoc.com/

**Comment by andrefarzat** [comment]
Hey, @josephfusco, I am ok with that.
Is it of for you if I create a repo called `cssdoc.net` here (thus url would be github.com/cssdoc/cssdoc.net ) and give you the permissions?
Will you set up using the http://cssdoc.net url on you want to use github pages (i.e.: cssdoc.github.io ) ?

**Comment by josephfusco** [comment]
Great! We probably won't be able to get that domain as I haven't heard back from any of those developers and the site was abandoned.

Yes GitHub pages would be used for this. Can we name the repo `cssdoc.github.io` so it can be used as the main subdomain? That way it's not a directory site like cssdoc.github.io/cssdoc.net. :)

**Comment by andrefarzat** [comment]
I created the repo as you asked and added you there. Have fun :)

**Comment by josephfusco** [comment]
Great thanks @andrefarzat ! 👍
